version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  web:
    docker:
      - image: cimg/node:15.1

    steps:
      - checkout
      - run: cd web && npm install
      - run: cd web && npm run test
      - run: cd web && npm run build

  server:
    docker:
      - image: cimg/node:15.1

    steps:
      - checkout
      - run: cd server && npm install

workflows:
  CI:
    jobs:
      - web
      - server
