version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2.6

jobs:
  web:
    docker:
      - image: cimg/node:15.1

    steps:
      - checkout
      - run: cd web && npm install
      - run: cd web && npm run test
      - run: cd web && npm run build

  server:
    docker:
      - image: cimg/node:15.1

    steps:
      - checkout
      - run: cd server && npm install

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install

workflows:
  heroku_deploy:
    jobs:
      - web
      - server
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - web
            - server
          deploy:
            pre-steps:
              - run:
                command: cd server && npm start
                name: Run Node Application
          # pre-steps:
          #   - run:
          #     command: cd server && npm start
          #     name: Run Node Application
