version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2.6

jobs:
  web:
    docker:
      - image: cimg/node:15.1

    steps:
      - checkout
      - run: pwd
      - run: cd web && npm install
      - run: cd web && npm run test
      - run: cd web && npm run build

  server:
    docker:
      - image: cimg/node:15.1

    steps:
      - checkout
      - run: npm install

  heroku_deploy:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  CI:
    jobs:
      - web
      - server
      - heroku_deploy:
          requires:
            - web
            - server
