const types = {
  REGISTER_FAMILY_AND_USER: "REGISTER_FAMILY_AND_USER",
  IS_LOADING: "IS_LOADING",
  REGISTER_FAMILY: "REGISTER_FAMILY",
  REGISTER_USER: "REGISTER_USER",
  LOGIN_USER: "LOGIN_USER",
  AUTH_ERROR: "AUTH_ERROR",
};

export default types;
